
print("Caixa:")
print("*********")
print("*       *")
print("*       *")
print("*********")

print("\nOval:")
print("   ***   ")
print(" *     * ")
print("*       *")
print(" *     * ")
print("   ***   ")

print("\nSeta:")
print("    *    ")
print("   ***   ")
print("  *****  ")
print("    *    ")
print("    *    ")

print("\nLosango:")
print("    *    ")
print("   * *   ")
print("  *   *  ")
print(" *     * ")
print("  *   *  ")
print("   * *   ")
print("    *    ")